name: benchmarks

on:
  push:
    paths:
      - datasets/**
      - models/**

permissions:
  contents: write

jobs:
  run-tests:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.9"
        dataset:
        - "{dataset_list}"
        model:
        - "{model_list}"


    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run-benchmarks
        shell: bash -l {0}
        run: |
          python command.py --models "${{ matrix.model }}" --datasets "${{ matrix.dataset }}"

      - name: commit-results
        run: | 
          git config --global user.name "Github Action"
          git config --global user.email "info@dreamfaster.ai"
          git pull
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "feature(Result): Added new benchmarking results for {dataset_names} - {model_names}."
          git push