name: benchmarks

on:
  pull_request: 
    paths:
      - datasets/**
      - models/**
      - '!frontend/src/datasets/**'
      - '!frontend/src/models/**'

permissions:
  contents: write

jobs:
  benchmark:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        dataset:
        - "m4"
        model:
        - "BaselineNaive"
        - "BaselineNaiveSeasonal"
        - "StatsModelARIMAOne"
        - "StatsForecastARIMAOne"


    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run-benchmarks
        shell: bash -l {0}
        run: |
          python command.py --models "${{ matrix.model }}" --datasets "${{ matrix.dataset }}"

      - name: commit-results
        run: | 
          git config --global user.name "Github Action"
          git config --global user.email "info@dreamfaster.ai"
          git fetch
          git pull
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "feature(Result): Added new results for ${{ matrix.dataset }} - ${{ matrix.model }}"
          git push
