name: tests

on:
  push:

jobs:

  run-tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
#        - macos-latest
#        - windows-latest
        python-version:
#        - "3.7"
#        - "3.8"
        - "3.9"
#        - "3.10"
#        - "3.11"

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: run-tests
      #   run: pytest tests/ -s --durations 0
      - name: Run pytest
        run: |
          pytest --junit-xml pytest.xml
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: pytest.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: pytest.xml        
